spring:
  application:
    name: chatcode
  datasource:
    url: jdbc:mysql://localhost:3306/chatcode
    username: root
    password: 1234
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: <GOOGLE_CLIENT_ID>
            client-secret: <GOOGLE_CLIENT_SECRET>
            scope:
              - email
              - profile
          github:
            client-id: <GITHUB_CLIENT_ID>
            client-secret: <GITHUB_CLIENT_SECRET> 
external:
  jwt:
    tokenSecretKey: cfc6f8968e16e357e2a588674174bc2ca34b538e9f759d081d48721fd0aa1f626188fca140ca58a5b88d6e98b3302c52f49f7fa1dc06924c34ecd45b31ba675e
    tokenPrefix: Bearer/u0020
    accessKey: Authorization
    refreshKey: RefreshToken
    accessTokenExpirationTime: 300000 # 5분
    refreshTokenExpirationTime: 900000 # 15분
    # 1000 * 60 * 60 * 24 * 7 = 604800000 1주일
    # 1000 * 60 * 30 = 1800000 30