spring:
  application:
    name: chatcode
  config:
    import:
      - classpath:application-dev.yaml
      - classpath:application-prod.yaml
      - classpath:/yaml/application-oauth2.yaml
      - classpath:/yaml/application-log.yaml
      - classpath:/yaml/application-jwt.yaml
  profiles:
    group:
      develop: dev, oauth2, jwt, log
      production: prod, oauth2, jwt
    active: develop