/*
 * This file is generated by jOOQ.
 */
package com.chatcode.jooq.tables;


import com.chatcode.jooq.DefaultSchema;
import com.chatcode.jooq.Keys;
import com.chatcode.jooq.tables.records._28optional_29notificationReadRecord;

import java.time.LocalDateTime;
import java.util.Collection;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class _28optional_29notificationRead extends TableImpl<_28optional_29notificationReadRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>(optional)notification_read</code>
     */
    public static final _28optional_29notificationRead _28OPTIONAL_29NOTIFICATION_READ = new _28optional_29notificationRead();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<_28optional_29notificationReadRecord> getRecordType() {
        return _28optional_29notificationReadRecord.class;
    }

    /**
     * The column <code>(optional)notification_read.id</code>.
     */
    public final TableField<_28optional_29notificationReadRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>(optional)notification_read.avatar_id</code>.
     */
    public final TableField<_28optional_29notificationReadRecord, Long> AVATAR_ID = createField(DSL.name("avatar_id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>(optional)notification_read.version</code>.
     */
    public final TableField<_28optional_29notificationReadRecord, Long> VERSION = createField(DSL.name("version"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>(optional)notification_read.last_read</code>.
     */
    public final TableField<_28optional_29notificationReadRecord, LocalDateTime> LAST_READ = createField(DSL.name("last_read"), SQLDataType.LOCALDATETIME(6).nullable(false), this, "");

    private _28optional_29notificationRead(Name alias, Table<_28optional_29notificationReadRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private _28optional_29notificationRead(Name alias, Table<_28optional_29notificationReadRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>(optional)notification_read</code> table
     * reference
     */
    public _28optional_29notificationRead(String alias) {
        this(DSL.name(alias), _28OPTIONAL_29NOTIFICATION_READ);
    }

    /**
     * Create an aliased <code>(optional)notification_read</code> table
     * reference
     */
    public _28optional_29notificationRead(Name alias) {
        this(alias, _28OPTIONAL_29NOTIFICATION_READ);
    }

    /**
     * Create a <code>(optional)notification_read</code> table reference
     */
    public _28optional_29notificationRead() {
        this(DSL.name("(optional)notification_read"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : DefaultSchema.DEFAULT_SCHEMA;
    }

    @Override
    public UniqueKey<_28optional_29notificationReadRecord> getPrimaryKey() {
        return Keys.PK__28OPTIONAL_29NOTIFICATION_READ;
    }

    @Override
    public _28optional_29notificationRead as(String alias) {
        return new _28optional_29notificationRead(DSL.name(alias), this);
    }

    @Override
    public _28optional_29notificationRead as(Name alias) {
        return new _28optional_29notificationRead(alias, this);
    }

    @Override
    public _28optional_29notificationRead as(Table<?> alias) {
        return new _28optional_29notificationRead(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public _28optional_29notificationRead rename(String name) {
        return new _28optional_29notificationRead(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public _28optional_29notificationRead rename(Name name) {
        return new _28optional_29notificationRead(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public _28optional_29notificationRead rename(Table<?> name) {
        return new _28optional_29notificationRead(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public _28optional_29notificationRead where(Condition condition) {
        return new _28optional_29notificationRead(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public _28optional_29notificationRead where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public _28optional_29notificationRead where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public _28optional_29notificationRead where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public _28optional_29notificationRead where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public _28optional_29notificationRead where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public _28optional_29notificationRead where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public _28optional_29notificationRead where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public _28optional_29notificationRead whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public _28optional_29notificationRead whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
