/*
 * This file is generated by jOOQ.
 */
package com.chatcode.jooq.tables;


import com.chatcode.jooq.DefaultSchema;
import com.chatcode.jooq.Keys;
import com.chatcode.jooq.tables.records.AreaDistrictCodeRecord;

import java.util.Collection;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AreaDistrictCode extends TableImpl<AreaDistrictCodeRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>area_district_code</code>
     */
    public static final AreaDistrictCode AREA_DISTRICT_CODE = new AreaDistrictCode();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<AreaDistrictCodeRecord> getRecordType() {
        return AreaDistrictCodeRecord.class;
    }

    /**
     * The column <code>area_district_code.id</code>.
     */
    public final TableField<AreaDistrictCodeRecord, String> ID = createField(DSL.name("id"), SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>area_district_code.version</code>.
     */
    public final TableField<AreaDistrictCodeRecord, Long> VERSION = createField(DSL.name("version"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>area_district_code.area_city_code_id</code>.
     */
    public final TableField<AreaDistrictCodeRecord, String> AREA_CITY_CODE_ID = createField(DSL.name("area_city_code_id"), SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>area_district_code.name</code>.
     */
    public final TableField<AreaDistrictCodeRecord, String> NAME = createField(DSL.name("name"), SQLDataType.VARCHAR(255).nullable(false), this, "");

    private AreaDistrictCode(Name alias, Table<AreaDistrictCodeRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private AreaDistrictCode(Name alias, Table<AreaDistrictCodeRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>area_district_code</code> table reference
     */
    public AreaDistrictCode(String alias) {
        this(DSL.name(alias), AREA_DISTRICT_CODE);
    }

    /**
     * Create an aliased <code>area_district_code</code> table reference
     */
    public AreaDistrictCode(Name alias) {
        this(alias, AREA_DISTRICT_CODE);
    }

    /**
     * Create a <code>area_district_code</code> table reference
     */
    public AreaDistrictCode() {
        this(DSL.name("area_district_code"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : DefaultSchema.DEFAULT_SCHEMA;
    }

    @Override
    public UniqueKey<AreaDistrictCodeRecord> getPrimaryKey() {
        return Keys.PK_AREA_DISTRICT_CODE;
    }

    @Override
    public AreaDistrictCode as(String alias) {
        return new AreaDistrictCode(DSL.name(alias), this);
    }

    @Override
    public AreaDistrictCode as(Name alias) {
        return new AreaDistrictCode(alias, this);
    }

    @Override
    public AreaDistrictCode as(Table<?> alias) {
        return new AreaDistrictCode(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public AreaDistrictCode rename(String name) {
        return new AreaDistrictCode(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public AreaDistrictCode rename(Name name) {
        return new AreaDistrictCode(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public AreaDistrictCode rename(Table<?> name) {
        return new AreaDistrictCode(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AreaDistrictCode where(Condition condition) {
        return new AreaDistrictCode(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AreaDistrictCode where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AreaDistrictCode where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AreaDistrictCode where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public AreaDistrictCode where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public AreaDistrictCode where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public AreaDistrictCode where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public AreaDistrictCode where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AreaDistrictCode whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AreaDistrictCode whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
