/*
 * This file is generated by jOOQ.
 */
package com.chatcode.jooq.tables;


import com.chatcode.jooq.DefaultSchema;
import com.chatcode.jooq.tables.records.AvatarInterestTagRecord;

import java.util.Collection;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AvatarInterestTag extends TableImpl<AvatarInterestTagRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>avatar_interest_tag</code>
     */
    public static final AvatarInterestTag AVATAR_INTEREST_TAG = new AvatarInterestTag();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<AvatarInterestTagRecord> getRecordType() {
        return AvatarInterestTagRecord.class;
    }

    /**
     * The column <code>avatar_interest_tag.avtar_id</code>.
     */
    public final TableField<AvatarInterestTagRecord, Long> AVTAR_ID = createField(DSL.name("avtar_id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>avatar_interest_tag.name</code>.
     */
    public final TableField<AvatarInterestTagRecord, String> NAME = createField(DSL.name("name"), SQLDataType.VARCHAR(255).nullable(false), this, "");

    private AvatarInterestTag(Name alias, Table<AvatarInterestTagRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private AvatarInterestTag(Name alias, Table<AvatarInterestTagRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>avatar_interest_tag</code> table reference
     */
    public AvatarInterestTag(String alias) {
        this(DSL.name(alias), AVATAR_INTEREST_TAG);
    }

    /**
     * Create an aliased <code>avatar_interest_tag</code> table reference
     */
    public AvatarInterestTag(Name alias) {
        this(alias, AVATAR_INTEREST_TAG);
    }

    /**
     * Create a <code>avatar_interest_tag</code> table reference
     */
    public AvatarInterestTag() {
        this(DSL.name("avatar_interest_tag"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : DefaultSchema.DEFAULT_SCHEMA;
    }

    @Override
    public AvatarInterestTag as(String alias) {
        return new AvatarInterestTag(DSL.name(alias), this);
    }

    @Override
    public AvatarInterestTag as(Name alias) {
        return new AvatarInterestTag(alias, this);
    }

    @Override
    public AvatarInterestTag as(Table<?> alias) {
        return new AvatarInterestTag(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public AvatarInterestTag rename(String name) {
        return new AvatarInterestTag(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public AvatarInterestTag rename(Name name) {
        return new AvatarInterestTag(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public AvatarInterestTag rename(Table<?> name) {
        return new AvatarInterestTag(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AvatarInterestTag where(Condition condition) {
        return new AvatarInterestTag(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AvatarInterestTag where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AvatarInterestTag where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AvatarInterestTag where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public AvatarInterestTag where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public AvatarInterestTag where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public AvatarInterestTag where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public AvatarInterestTag where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AvatarInterestTag whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AvatarInterestTag whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
