/*
 * This file is generated by jOOQ.
 */
package com.chatcode.jooq.tables;


import com.chatcode.jooq.DefaultSchema;
import com.chatcode.jooq.Keys;
import com.chatcode.jooq.tables.records.BannerClickRecord;

import java.time.LocalDateTime;
import java.util.Collection;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class BannerClick extends TableImpl<BannerClickRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>banner_click</code>
     */
    public static final BannerClick BANNER_CLICK = new BannerClick();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<BannerClickRecord> getRecordType() {
        return BannerClickRecord.class;
    }

    /**
     * The column <code>banner_click.id</code>.
     */
    public final TableField<BannerClickRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>banner_click.version</code>.
     */
    public final TableField<BannerClickRecord, Long> VERSION = createField(DSL.name("version"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>banner_click.banner_id</code>.
     */
    public final TableField<BannerClickRecord, Long> BANNER_ID = createField(DSL.name("banner_id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>banner_click.click_count</code>.
     */
    public final TableField<BannerClickRecord, Integer> CLICK_COUNT = createField(DSL.name("click_count"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>banner_click.date_created</code>.
     */
    public final TableField<BannerClickRecord, LocalDateTime> DATE_CREATED = createField(DSL.name("date_created"), SQLDataType.LOCALDATETIME(6).nullable(false), this, "");

    /**
     * The column <code>banner_click.ip</code>.
     */
    public final TableField<BannerClickRecord, String> IP = createField(DSL.name("ip"), SQLDataType.VARCHAR(255).nullable(false), this, "");

    private BannerClick(Name alias, Table<BannerClickRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private BannerClick(Name alias, Table<BannerClickRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>banner_click</code> table reference
     */
    public BannerClick(String alias) {
        this(DSL.name(alias), BANNER_CLICK);
    }

    /**
     * Create an aliased <code>banner_click</code> table reference
     */
    public BannerClick(Name alias) {
        this(alias, BANNER_CLICK);
    }

    /**
     * Create a <code>banner_click</code> table reference
     */
    public BannerClick() {
        this(DSL.name("banner_click"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : DefaultSchema.DEFAULT_SCHEMA;
    }

    @Override
    public UniqueKey<BannerClickRecord> getPrimaryKey() {
        return Keys.PK_BANNER_CLICK;
    }

    @Override
    public BannerClick as(String alias) {
        return new BannerClick(DSL.name(alias), this);
    }

    @Override
    public BannerClick as(Name alias) {
        return new BannerClick(alias, this);
    }

    @Override
    public BannerClick as(Table<?> alias) {
        return new BannerClick(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public BannerClick rename(String name) {
        return new BannerClick(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public BannerClick rename(Name name) {
        return new BannerClick(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public BannerClick rename(Table<?> name) {
        return new BannerClick(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public BannerClick where(Condition condition) {
        return new BannerClick(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public BannerClick where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public BannerClick where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public BannerClick where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public BannerClick where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public BannerClick where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public BannerClick where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public BannerClick where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public BannerClick whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public BannerClick whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
