/*
 * This file is generated by jOOQ.
 */
package com.chatcode.jooq.tables;


import com.chatcode.jooq.DefaultSchema;
import com.chatcode.jooq.Keys;
import com.chatcode.jooq.tables.records.ContentVoteRecord;

import java.time.LocalDateTime;
import java.util.Collection;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ContentVote extends TableImpl<ContentVoteRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>content_vote</code>
     */
    public static final ContentVote CONTENT_VOTE = new ContentVote();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ContentVoteRecord> getRecordType() {
        return ContentVoteRecord.class;
    }

    /**
     * The column <code>content_vote.id</code>.
     */
    public final TableField<ContentVoteRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>content_vote.article_id</code>.
     */
    public final TableField<ContentVoteRecord, Long> ARTICLE_ID = createField(DSL.name("article_id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>content_vote.voter_id</code>.
     */
    public final TableField<ContentVoteRecord, Long> VOTER_ID = createField(DSL.name("voter_id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>content_vote.content_id</code>.
     */
    public final TableField<ContentVoteRecord, Long> CONTENT_ID = createField(DSL.name("content_id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>content_vote.date_created</code>.
     */
    public final TableField<ContentVoteRecord, LocalDateTime> DATE_CREATED = createField(DSL.name("date_created"), SQLDataType.LOCALDATETIME(6).nullable(false), this, "");

    /**
     * The column <code>content_vote.point</code>.
     */
    public final TableField<ContentVoteRecord, Integer> POINT = createField(DSL.name("point"), SQLDataType.INTEGER.nullable(false), this, "");

    private ContentVote(Name alias, Table<ContentVoteRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private ContentVote(Name alias, Table<ContentVoteRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>content_vote</code> table reference
     */
    public ContentVote(String alias) {
        this(DSL.name(alias), CONTENT_VOTE);
    }

    /**
     * Create an aliased <code>content_vote</code> table reference
     */
    public ContentVote(Name alias) {
        this(alias, CONTENT_VOTE);
    }

    /**
     * Create a <code>content_vote</code> table reference
     */
    public ContentVote() {
        this(DSL.name("content_vote"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : DefaultSchema.DEFAULT_SCHEMA;
    }

    @Override
    public UniqueKey<ContentVoteRecord> getPrimaryKey() {
        return Keys.PK_CONTENT_VOTE;
    }

    @Override
    public ContentVote as(String alias) {
        return new ContentVote(DSL.name(alias), this);
    }

    @Override
    public ContentVote as(Name alias) {
        return new ContentVote(alias, this);
    }

    @Override
    public ContentVote as(Table<?> alias) {
        return new ContentVote(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public ContentVote rename(String name) {
        return new ContentVote(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public ContentVote rename(Name name) {
        return new ContentVote(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public ContentVote rename(Table<?> name) {
        return new ContentVote(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ContentVote where(Condition condition) {
        return new ContentVote(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ContentVote where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ContentVote where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ContentVote where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ContentVote where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ContentVote where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ContentVote where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ContentVote where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ContentVote whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ContentVote whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
