/*
 * This file is generated by jOOQ.
 */
package com.chatcode.jooq.tables;


import com.chatcode.jooq.DefaultSchema;
import com.chatcode.jooq.Keys;
import com.chatcode.jooq.tables.records.LoggedInRecord;

import java.time.LocalDateTime;
import java.util.Collection;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class LoggedIn extends TableImpl<LoggedInRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>logged_in</code>
     */
    public static final LoggedIn LOGGED_IN = new LoggedIn();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<LoggedInRecord> getRecordType() {
        return LoggedInRecord.class;
    }

    /**
     * The column <code>logged_in.id</code>.
     */
    public final TableField<LoggedInRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>logged_in.user_id</code>.
     */
    public final TableField<LoggedInRecord, Long> USER_ID = createField(DSL.name("user_id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>logged_in.version</code>.
     */
    public final TableField<LoggedInRecord, Long> VERSION = createField(DSL.name("version"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>logged_in.date_created</code>.
     */
    public final TableField<LoggedInRecord, LocalDateTime> DATE_CREATED = createField(DSL.name("date_created"), SQLDataType.LOCALDATETIME(6).nullable(false), this, "");

    /**
     * The column <code>logged_in.remote_addr</code>.
     */
    public final TableField<LoggedInRecord, String> REMOTE_ADDR = createField(DSL.name("remote_addr"), SQLDataType.VARCHAR(255), this, "");

    private LoggedIn(Name alias, Table<LoggedInRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private LoggedIn(Name alias, Table<LoggedInRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>logged_in</code> table reference
     */
    public LoggedIn(String alias) {
        this(DSL.name(alias), LOGGED_IN);
    }

    /**
     * Create an aliased <code>logged_in</code> table reference
     */
    public LoggedIn(Name alias) {
        this(alias, LOGGED_IN);
    }

    /**
     * Create a <code>logged_in</code> table reference
     */
    public LoggedIn() {
        this(DSL.name("logged_in"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : DefaultSchema.DEFAULT_SCHEMA;
    }

    @Override
    public UniqueKey<LoggedInRecord> getPrimaryKey() {
        return Keys.PK_LOGGED_IN;
    }

    @Override
    public LoggedIn as(String alias) {
        return new LoggedIn(DSL.name(alias), this);
    }

    @Override
    public LoggedIn as(Name alias) {
        return new LoggedIn(alias, this);
    }

    @Override
    public LoggedIn as(Table<?> alias) {
        return new LoggedIn(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public LoggedIn rename(String name) {
        return new LoggedIn(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public LoggedIn rename(Name name) {
        return new LoggedIn(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public LoggedIn rename(Table<?> name) {
        return new LoggedIn(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public LoggedIn where(Condition condition) {
        return new LoggedIn(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public LoggedIn where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public LoggedIn where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public LoggedIn where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public LoggedIn where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public LoggedIn where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public LoggedIn where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public LoggedIn where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public LoggedIn whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public LoggedIn whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
