version: "2.2"
services:
  mysql:
    container_name: "Chatcode_DB"
    image: mysql:8.0
    command: >
      bash -c "
      chmod 644 /etc/mysql/conf.d/*.cnf
      && /entrypoint.sh mysqld
      "
    ports:
      - "3306:3306"
    env_file: .env.mysql
    environment:
      TZ: UTC
    volumes:
      - ${DEFAULT_PATH}/mysql/conf.d:/etc/mysql/conf.d
      - ${DEFAULT_PATH}/mysql/data:/var/lib/mysql
      - ${DEFAULT_PATH}/mysql/initdb.d:/docker-entrypoint-initdb.d
    restart: always

  redis:
    container_name: "Chatcode_Redis"
    image: redis:7.2.4
    ports:
      - "6379:6379"
    restart: always
