/*
 * This file is generated by jOOQ.
 */
package com.chatcode.jooq;


import com.chatcode.jooq.tables.AreaDistrictCode;
import com.chatcode.jooq.tables.Article;
import com.chatcode.jooq.tables.AvatarInterestTag;
import com.chatcode.jooq.tables.UserRole;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Chatcode extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>CHATCODE</code>
     */
    public static final Chatcode CHATCODE = new Chatcode();

    /**
     * The table <code>CHATCODE.area_district_code</code>.
     */
    public final AreaDistrictCode AREA_DISTRICT_CODE = AreaDistrictCode.AREA_DISTRICT_CODE;

    /**
     * The table <code>CHATCODE.article</code>.
     */
    public final Article ARTICLE = Article.ARTICLE;

    /**
     * The table <code>CHATCODE.avatar_interest_tag</code>.
     */
    public final AvatarInterestTag AVATAR_INTEREST_TAG = AvatarInterestTag.AVATAR_INTEREST_TAG;

    /**
     * The table <code>CHATCODE.user_role</code>.
     */
    public final UserRole USER_ROLE = UserRole.USER_ROLE;

    /**
     * No further instances allowed
     */
    private Chatcode() {
        super("CHATCODE", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            AreaDistrictCode.AREA_DISTRICT_CODE,
            Article.ARTICLE,
            AvatarInterestTag.AVATAR_INTEREST_TAG,
            UserRole.USER_ROLE
        );
    }
}
