/*
 * This file is generated by jOOQ.
 */
package com.chatcode.jooq;


import com.chatcode.jooq.tables.Activity;
import com.chatcode.jooq.tables.AreaCityCode;
import com.chatcode.jooq.tables.AreaDistrictCode;
import com.chatcode.jooq.tables.Article;
import com.chatcode.jooq.tables.ArticleTag;
import com.chatcode.jooq.tables.Avatar;
import com.chatcode.jooq.tables.AvatarInterestTag;
import com.chatcode.jooq.tables.Banner;
import com.chatcode.jooq.tables.BannerClick;
import com.chatcode.jooq.tables.Category;
import com.chatcode.jooq.tables.CategoryOld;
import com.chatcode.jooq.tables.ChangeLog;
import com.chatcode.jooq.tables.ConfirmEmail;
import com.chatcode.jooq.tables.Content;
import com.chatcode.jooq.tables.ContentFile;
import com.chatcode.jooq.tables.ContentVote;
import com.chatcode.jooq.tables.File;
import com.chatcode.jooq.tables.Follow;
import com.chatcode.jooq.tables.InterestTag;
import com.chatcode.jooq.tables.LoggedIn;
import com.chatcode.jooq.tables.Oauthid;
import com.chatcode.jooq.tables.Opinion;
import com.chatcode.jooq.tables.Role;
import com.chatcode.jooq.tables.Scrap;
import com.chatcode.jooq.tables.SpamWord;
import com.chatcode.jooq.tables.Tag;
import com.chatcode.jooq.tables.TempArticle;
import com.chatcode.jooq.tables.User;
import com.chatcode.jooq.tables.UserRole;
import com.chatcode.jooq.tables._28optional_29notification;
import com.chatcode.jooq.tables._28optional_29notificationRead;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DefaultSchema extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>DEFAULT_SCHEMA</code>
     */
    public static final DefaultSchema DEFAULT_SCHEMA = new DefaultSchema();

    /**
     * The table <code>(optional)notification</code>.
     */
    public final _28optional_29notification _28OPTIONAL_29NOTIFICATION = _28optional_29notification._28OPTIONAL_29NOTIFICATION;

    /**
     * The table <code>(optional)notification_read</code>.
     */
    public final _28optional_29notificationRead _28OPTIONAL_29NOTIFICATION_READ = _28optional_29notificationRead._28OPTIONAL_29NOTIFICATION_READ;

    /**
     * The table <code>activity</code>.
     */
    public final Activity ACTIVITY = Activity.ACTIVITY;

    /**
     * The table <code>area_city_code</code>.
     */
    public final AreaCityCode AREA_CITY_CODE = AreaCityCode.AREA_CITY_CODE;

    /**
     * The table <code>area_district_code</code>.
     */
    public final AreaDistrictCode AREA_DISTRICT_CODE = AreaDistrictCode.AREA_DISTRICT_CODE;

    /**
     * The table <code>article</code>.
     */
    public final Article ARTICLE = Article.ARTICLE;

    /**
     * The table <code>article_tag</code>.
     */
    public final ArticleTag ARTICLE_TAG = ArticleTag.ARTICLE_TAG;

    /**
     * The table <code>avatar</code>.
     */
    public final Avatar AVATAR = Avatar.AVATAR;

    /**
     * The table <code>avatar_interest_tag</code>.
     */
    public final AvatarInterestTag AVATAR_INTEREST_TAG = AvatarInterestTag.AVATAR_INTEREST_TAG;

    /**
     * The table <code>banner</code>.
     */
    public final Banner BANNER = Banner.BANNER;

    /**
     * The table <code>banner_click</code>.
     */
    public final BannerClick BANNER_CLICK = BannerClick.BANNER_CLICK;

    /**
     * The table <code>category</code>.
     */
    public final Category CATEGORY = Category.CATEGORY;

    /**
     * The table <code>category_old</code>.
     */
    public final CategoryOld CATEGORY_OLD = CategoryOld.CATEGORY_OLD;

    /**
     * The table <code>change_log</code>.
     */
    public final ChangeLog CHANGE_LOG = ChangeLog.CHANGE_LOG;

    /**
     * The table <code>confirm_email</code>.
     */
    public final ConfirmEmail CONFIRM_EMAIL = ConfirmEmail.CONFIRM_EMAIL;

    /**
     * The table <code>content</code>.
     */
    public final Content CONTENT = Content.CONTENT;

    /**
     * The table <code>content_file</code>.
     */
    public final ContentFile CONTENT_FILE = ContentFile.CONTENT_FILE;

    /**
     * The table <code>content_vote</code>.
     */
    public final ContentVote CONTENT_VOTE = ContentVote.CONTENT_VOTE;

    /**
     * The table <code>file</code>.
     */
    public final File FILE = File.FILE;

    /**
     * The table <code>follow</code>.
     */
    public final Follow FOLLOW = Follow.FOLLOW;

    /**
     * The table <code>interest_tag</code>.
     */
    public final InterestTag INTEREST_TAG = InterestTag.INTEREST_TAG;

    /**
     * The table <code>logged_in</code>.
     */
    public final LoggedIn LOGGED_IN = LoggedIn.LOGGED_IN;

    /**
     * The table <code>oauthid</code>.
     */
    public final Oauthid OAUTHID = Oauthid.OAUTHID;

    /**
     * The table <code>opinion</code>.
     */
    public final Opinion OPINION = Opinion.OPINION;

    /**
     * The table <code>role</code>.
     */
    public final Role ROLE = Role.ROLE;

    /**
     * The table <code>scrap</code>.
     */
    public final Scrap SCRAP = Scrap.SCRAP;

    /**
     * The table <code>spam_word</code>.
     */
    public final SpamWord SPAM_WORD = SpamWord.SPAM_WORD;

    /**
     * The table <code>tag</code>.
     */
    public final Tag TAG = Tag.TAG;

    /**
     * The table <code>temp_article</code>.
     */
    public final TempArticle TEMP_ARTICLE = TempArticle.TEMP_ARTICLE;

    /**
     * The table <code>user</code>.
     */
    public final User USER = User.USER;

    /**
     * The table <code>user_role</code>.
     */
    public final UserRole USER_ROLE = UserRole.USER_ROLE;

    /**
     * No further instances allowed
     */
    private DefaultSchema() {
        super("", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            _28optional_29notification._28OPTIONAL_29NOTIFICATION,
            _28optional_29notificationRead._28OPTIONAL_29NOTIFICATION_READ,
            Activity.ACTIVITY,
            AreaCityCode.AREA_CITY_CODE,
            AreaDistrictCode.AREA_DISTRICT_CODE,
            Article.ARTICLE,
            ArticleTag.ARTICLE_TAG,
            Avatar.AVATAR,
            AvatarInterestTag.AVATAR_INTEREST_TAG,
            Banner.BANNER,
            BannerClick.BANNER_CLICK,
            Category.CATEGORY,
            CategoryOld.CATEGORY_OLD,
            ChangeLog.CHANGE_LOG,
            ConfirmEmail.CONFIRM_EMAIL,
            Content.CONTENT,
            ContentFile.CONTENT_FILE,
            ContentVote.CONTENT_VOTE,
            File.FILE,
            Follow.FOLLOW,
            InterestTag.INTEREST_TAG,
            LoggedIn.LOGGED_IN,
            Oauthid.OAUTHID,
            Opinion.OPINION,
            Role.ROLE,
            Scrap.SCRAP,
            SpamWord.SPAM_WORD,
            Tag.TAG,
            TempArticle.TEMP_ARTICLE,
            User.USER,
            UserRole.USER_ROLE
        );
    }
}
