/*
 * This file is generated by jOOQ.
 */
package com.chatcode.jooq.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class _28optional_29notificationRead implements Serializable {

    private static final long serialVersionUID = 1L;

    private final Long id;
    private final Long avatarId;
    private final Long version;
    private final LocalDateTime lastRead;

    public _28optional_29notificationRead(_28optional_29notificationRead value) {
        this.id = value.id;
        this.avatarId = value.avatarId;
        this.version = value.version;
        this.lastRead = value.lastRead;
    }

    public _28optional_29notificationRead(
        Long id,
        Long avatarId,
        Long version,
        LocalDateTime lastRead
    ) {
        this.id = id;
        this.avatarId = avatarId;
        this.version = version;
        this.lastRead = lastRead;
    }

    /**
     * Getter for <code>(optional)notification_read.id</code>.
     */
    public Long getId() {
        return this.id;
    }

    /**
     * Getter for <code>(optional)notification_read.avatar_id</code>.
     */
    public Long getAvatarId() {
        return this.avatarId;
    }

    /**
     * Getter for <code>(optional)notification_read.version</code>.
     */
    public Long getVersion() {
        return this.version;
    }

    /**
     * Getter for <code>(optional)notification_read.last_read</code>.
     */
    public LocalDateTime getLastRead() {
        return this.lastRead;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final _28optional_29notificationRead other = (_28optional_29notificationRead) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.avatarId == null) {
            if (other.avatarId != null)
                return false;
        }
        else if (!this.avatarId.equals(other.avatarId))
            return false;
        if (this.version == null) {
            if (other.version != null)
                return false;
        }
        else if (!this.version.equals(other.version))
            return false;
        if (this.lastRead == null) {
            if (other.lastRead != null)
                return false;
        }
        else if (!this.lastRead.equals(other.lastRead))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.avatarId == null) ? 0 : this.avatarId.hashCode());
        result = prime * result + ((this.version == null) ? 0 : this.version.hashCode());
        result = prime * result + ((this.lastRead == null) ? 0 : this.lastRead.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("_28optional_29notificationRead (");

        sb.append(id);
        sb.append(", ").append(avatarId);
        sb.append(", ").append(version);
        sb.append(", ").append(lastRead);

        sb.append(")");
        return sb.toString();
    }
}
