/*
 * This file is generated by jOOQ.
 */
package com.chatcode.jooq.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Activity implements Serializable {

    private static final long serialVersionUID = 1L;

    private final Long id;
    private final Long avatarId;
    private final Long articleId;
    private final Long contentId;
    private final Long version;
    private final LocalDateTime dateCreated;
    private final LocalDateTime lastUpdated;
    private final Integer point;
    private final String pointType;
    private final String type;

    public Activity(Activity value) {
        this.id = value.id;
        this.avatarId = value.avatarId;
        this.articleId = value.articleId;
        this.contentId = value.contentId;
        this.version = value.version;
        this.dateCreated = value.dateCreated;
        this.lastUpdated = value.lastUpdated;
        this.point = value.point;
        this.pointType = value.pointType;
        this.type = value.type;
    }

    public Activity(
        Long id,
        Long avatarId,
        Long articleId,
        Long contentId,
        Long version,
        LocalDateTime dateCreated,
        LocalDateTime lastUpdated,
        Integer point,
        String pointType,
        String type
    ) {
        this.id = id;
        this.avatarId = avatarId;
        this.articleId = articleId;
        this.contentId = contentId;
        this.version = version;
        this.dateCreated = dateCreated;
        this.lastUpdated = lastUpdated;
        this.point = point;
        this.pointType = pointType;
        this.type = type;
    }

    /**
     * Getter for <code>activity.id</code>.
     */
    public Long getId() {
        return this.id;
    }

    /**
     * Getter for <code>activity.avatar_id</code>.
     */
    public Long getAvatarId() {
        return this.avatarId;
    }

    /**
     * Getter for <code>activity.article_id</code>.
     */
    public Long getArticleId() {
        return this.articleId;
    }

    /**
     * Getter for <code>activity.content_id</code>.
     */
    public Long getContentId() {
        return this.contentId;
    }

    /**
     * Getter for <code>activity.version</code>.
     */
    public Long getVersion() {
        return this.version;
    }

    /**
     * Getter for <code>activity.date_created</code>.
     */
    public LocalDateTime getDateCreated() {
        return this.dateCreated;
    }

    /**
     * Getter for <code>activity.last_updated</code>.
     */
    public LocalDateTime getLastUpdated() {
        return this.lastUpdated;
    }

    /**
     * Getter for <code>activity.point</code>.
     */
    public Integer getPoint() {
        return this.point;
    }

    /**
     * Getter for <code>activity.point_type</code>.
     */
    public String getPointType() {
        return this.pointType;
    }

    /**
     * Getter for <code>activity.type</code>.
     */
    public String getType() {
        return this.type;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final Activity other = (Activity) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.avatarId == null) {
            if (other.avatarId != null)
                return false;
        }
        else if (!this.avatarId.equals(other.avatarId))
            return false;
        if (this.articleId == null) {
            if (other.articleId != null)
                return false;
        }
        else if (!this.articleId.equals(other.articleId))
            return false;
        if (this.contentId == null) {
            if (other.contentId != null)
                return false;
        }
        else if (!this.contentId.equals(other.contentId))
            return false;
        if (this.version == null) {
            if (other.version != null)
                return false;
        }
        else if (!this.version.equals(other.version))
            return false;
        if (this.dateCreated == null) {
            if (other.dateCreated != null)
                return false;
        }
        else if (!this.dateCreated.equals(other.dateCreated))
            return false;
        if (this.lastUpdated == null) {
            if (other.lastUpdated != null)
                return false;
        }
        else if (!this.lastUpdated.equals(other.lastUpdated))
            return false;
        if (this.point == null) {
            if (other.point != null)
                return false;
        }
        else if (!this.point.equals(other.point))
            return false;
        if (this.pointType == null) {
            if (other.pointType != null)
                return false;
        }
        else if (!this.pointType.equals(other.pointType))
            return false;
        if (this.type == null) {
            if (other.type != null)
                return false;
        }
        else if (!this.type.equals(other.type))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.avatarId == null) ? 0 : this.avatarId.hashCode());
        result = prime * result + ((this.articleId == null) ? 0 : this.articleId.hashCode());
        result = prime * result + ((this.contentId == null) ? 0 : this.contentId.hashCode());
        result = prime * result + ((this.version == null) ? 0 : this.version.hashCode());
        result = prime * result + ((this.dateCreated == null) ? 0 : this.dateCreated.hashCode());
        result = prime * result + ((this.lastUpdated == null) ? 0 : this.lastUpdated.hashCode());
        result = prime * result + ((this.point == null) ? 0 : this.point.hashCode());
        result = prime * result + ((this.pointType == null) ? 0 : this.pointType.hashCode());
        result = prime * result + ((this.type == null) ? 0 : this.type.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Activity (");

        sb.append(id);
        sb.append(", ").append(avatarId);
        sb.append(", ").append(articleId);
        sb.append(", ").append(contentId);
        sb.append(", ").append(version);
        sb.append(", ").append(dateCreated);
        sb.append(", ").append(lastUpdated);
        sb.append(", ").append(point);
        sb.append(", ").append(pointType);
        sb.append(", ").append(type);

        sb.append(")");
        return sb.toString();
    }
}
