/*
 * This file is generated by jOOQ.
 */
package com.chatcode.jooq.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ArticleTag implements Serializable {

    private static final long serialVersionUID = 1L;

    private final Long articleTagsId;
    private final Long tagId;

    public ArticleTag(ArticleTag value) {
        this.articleTagsId = value.articleTagsId;
        this.tagId = value.tagId;
    }

    public ArticleTag(
        Long articleTagsId,
        Long tagId
    ) {
        this.articleTagsId = articleTagsId;
        this.tagId = tagId;
    }

    /**
     * Getter for <code>article_tag.article_tags_id</code>.
     */
    public Long getArticleTagsId() {
        return this.articleTagsId;
    }

    /**
     * Getter for <code>article_tag.tag_id</code>.
     */
    public Long getTagId() {
        return this.tagId;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final ArticleTag other = (ArticleTag) obj;
        if (this.articleTagsId == null) {
            if (other.articleTagsId != null)
                return false;
        }
        else if (!this.articleTagsId.equals(other.articleTagsId))
            return false;
        if (this.tagId == null) {
            if (other.tagId != null)
                return false;
        }
        else if (!this.tagId.equals(other.tagId))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.articleTagsId == null) ? 0 : this.articleTagsId.hashCode());
        result = prime * result + ((this.tagId == null) ? 0 : this.tagId.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("ArticleTag (");

        sb.append(articleTagsId);
        sb.append(", ").append(tagId);

        sb.append(")");
        return sb.toString();
    }
}
