/*
 * This file is generated by jOOQ.
 */
package com.chatcode.jooq.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AvatarInterestTag implements Serializable {

    private static final long serialVersionUID = 1L;

    private final Long avtarId;
    private final String name;

    public AvatarInterestTag(AvatarInterestTag value) {
        this.avtarId = value.avtarId;
        this.name = value.name;
    }

    public AvatarInterestTag(
        Long avtarId,
        String name
    ) {
        this.avtarId = avtarId;
        this.name = name;
    }

    /**
     * Getter for <code>avatar_interest_tag.avtar_id</code>.
     */
    public Long getAvtarId() {
        return this.avtarId;
    }

    /**
     * Getter for <code>avatar_interest_tag.name</code>.
     */
    public String getName() {
        return this.name;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final AvatarInterestTag other = (AvatarInterestTag) obj;
        if (this.avtarId == null) {
            if (other.avtarId != null)
                return false;
        }
        else if (!this.avtarId.equals(other.avtarId))
            return false;
        if (this.name == null) {
            if (other.name != null)
                return false;
        }
        else if (!this.name.equals(other.name))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.avtarId == null) ? 0 : this.avtarId.hashCode());
        result = prime * result + ((this.name == null) ? 0 : this.name.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("AvatarInterestTag (");

        sb.append(avtarId);
        sb.append(", ").append(name);

        sb.append(")");
        return sb.toString();
    }
}
