/*
 * This file is generated by jOOQ.
 */
package com.chatcode.jooq.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ConfirmEmail implements Serializable {

    private static final long serialVersionUID = 1L;

    private final Long id;
    private final Long userId;
    private final Long version;
    private final LocalDateTime dateExpired;
    private final String email;
    private final String securedKey;

    public ConfirmEmail(ConfirmEmail value) {
        this.id = value.id;
        this.userId = value.userId;
        this.version = value.version;
        this.dateExpired = value.dateExpired;
        this.email = value.email;
        this.securedKey = value.securedKey;
    }

    public ConfirmEmail(
        Long id,
        Long userId,
        Long version,
        LocalDateTime dateExpired,
        String email,
        String securedKey
    ) {
        this.id = id;
        this.userId = userId;
        this.version = version;
        this.dateExpired = dateExpired;
        this.email = email;
        this.securedKey = securedKey;
    }

    /**
     * Getter for <code>confirm_email.id</code>.
     */
    public Long getId() {
        return this.id;
    }

    /**
     * Getter for <code>confirm_email.user_id</code>.
     */
    public Long getUserId() {
        return this.userId;
    }

    /**
     * Getter for <code>confirm_email.version</code>.
     */
    public Long getVersion() {
        return this.version;
    }

    /**
     * Getter for <code>confirm_email.date_expired</code>.
     */
    public LocalDateTime getDateExpired() {
        return this.dateExpired;
    }

    /**
     * Getter for <code>confirm_email.email</code>.
     */
    public String getEmail() {
        return this.email;
    }

    /**
     * Getter for <code>confirm_email.secured_key</code>.
     */
    public String getSecuredKey() {
        return this.securedKey;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final ConfirmEmail other = (ConfirmEmail) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.userId == null) {
            if (other.userId != null)
                return false;
        }
        else if (!this.userId.equals(other.userId))
            return false;
        if (this.version == null) {
            if (other.version != null)
                return false;
        }
        else if (!this.version.equals(other.version))
            return false;
        if (this.dateExpired == null) {
            if (other.dateExpired != null)
                return false;
        }
        else if (!this.dateExpired.equals(other.dateExpired))
            return false;
        if (this.email == null) {
            if (other.email != null)
                return false;
        }
        else if (!this.email.equals(other.email))
            return false;
        if (this.securedKey == null) {
            if (other.securedKey != null)
                return false;
        }
        else if (!this.securedKey.equals(other.securedKey))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.userId == null) ? 0 : this.userId.hashCode());
        result = prime * result + ((this.version == null) ? 0 : this.version.hashCode());
        result = prime * result + ((this.dateExpired == null) ? 0 : this.dateExpired.hashCode());
        result = prime * result + ((this.email == null) ? 0 : this.email.hashCode());
        result = prime * result + ((this.securedKey == null) ? 0 : this.securedKey.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("ConfirmEmail (");

        sb.append(id);
        sb.append(", ").append(userId);
        sb.append(", ").append(version);
        sb.append(", ").append(dateExpired);
        sb.append(", ").append(email);
        sb.append(", ").append(securedKey);

        sb.append(")");
        return sb.toString();
    }
}
