/*
 * This file is generated by jOOQ.
 */
package com.chatcode.jooq.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Oauthid implements Serializable {

    private static final long serialVersionUID = 1L;

    private final Long id;
    private final Long userId;
    private final Long version;
    private final String accessToken;
    private final String provider;

    public Oauthid(Oauthid value) {
        this.id = value.id;
        this.userId = value.userId;
        this.version = value.version;
        this.accessToken = value.accessToken;
        this.provider = value.provider;
    }

    public Oauthid(
        Long id,
        Long userId,
        Long version,
        String accessToken,
        String provider
    ) {
        this.id = id;
        this.userId = userId;
        this.version = version;
        this.accessToken = accessToken;
        this.provider = provider;
    }

    /**
     * Getter for <code>oauthid.id</code>.
     */
    public Long getId() {
        return this.id;
    }

    /**
     * Getter for <code>oauthid.user_id</code>.
     */
    public Long getUserId() {
        return this.userId;
    }

    /**
     * Getter for <code>oauthid.version</code>.
     */
    public Long getVersion() {
        return this.version;
    }

    /**
     * Getter for <code>oauthid.access_token</code>.
     */
    public String getAccessToken() {
        return this.accessToken;
    }

    /**
     * Getter for <code>oauthid.provider</code>.
     */
    public String getProvider() {
        return this.provider;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final Oauthid other = (Oauthid) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.userId == null) {
            if (other.userId != null)
                return false;
        }
        else if (!this.userId.equals(other.userId))
            return false;
        if (this.version == null) {
            if (other.version != null)
                return false;
        }
        else if (!this.version.equals(other.version))
            return false;
        if (this.accessToken == null) {
            if (other.accessToken != null)
                return false;
        }
        else if (!this.accessToken.equals(other.accessToken))
            return false;
        if (this.provider == null) {
            if (other.provider != null)
                return false;
        }
        else if (!this.provider.equals(other.provider))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.userId == null) ? 0 : this.userId.hashCode());
        result = prime * result + ((this.version == null) ? 0 : this.version.hashCode());
        result = prime * result + ((this.accessToken == null) ? 0 : this.accessToken.hashCode());
        result = prime * result + ((this.provider == null) ? 0 : this.provider.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Oauthid (");

        sb.append(id);
        sb.append(", ").append(userId);
        sb.append(", ").append(version);
        sb.append(", ").append(accessToken);
        sb.append(", ").append(provider);

        sb.append(")");
        return sb.toString();
    }
}
