/*
 * This file is generated by jOOQ.
 */
package com.chatcode.jooq.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Role implements Serializable {

    private static final long serialVersionUID = 1L;

    private final Long id;
    private final Long version;
    private final String authority;

    public Role(Role value) {
        this.id = value.id;
        this.version = value.version;
        this.authority = value.authority;
    }

    public Role(
        Long id,
        Long version,
        String authority
    ) {
        this.id = id;
        this.version = version;
        this.authority = authority;
    }

    /**
     * Getter for <code>role.id</code>.
     */
    public Long getId() {
        return this.id;
    }

    /**
     * Getter for <code>role.version</code>.
     */
    public Long getVersion() {
        return this.version;
    }

    /**
     * Getter for <code>role.authority</code>.
     */
    public String getAuthority() {
        return this.authority;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final Role other = (Role) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.version == null) {
            if (other.version != null)
                return false;
        }
        else if (!this.version.equals(other.version))
            return false;
        if (this.authority == null) {
            if (other.authority != null)
                return false;
        }
        else if (!this.authority.equals(other.authority))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.version == null) ? 0 : this.version.hashCode());
        result = prime * result + ((this.authority == null) ? 0 : this.authority.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Role (");

        sb.append(id);
        sb.append(", ").append(version);
        sb.append(", ").append(authority);

        sb.append(")");
        return sb.toString();
    }
}
