/*
 * This file is generated by jOOQ.
 */
package com.chatcode.jooq.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SpamWord implements Serializable {

    private static final long serialVersionUID = 1L;

    private final Long id;
    private final Long version;
    private final String text;

    public SpamWord(SpamWord value) {
        this.id = value.id;
        this.version = value.version;
        this.text = value.text;
    }

    public SpamWord(
        Long id,
        Long version,
        String text
    ) {
        this.id = id;
        this.version = version;
        this.text = text;
    }

    /**
     * Getter for <code>spam_word.id</code>.
     */
    public Long getId() {
        return this.id;
    }

    /**
     * Getter for <code>spam_word.version</code>.
     */
    public Long getVersion() {
        return this.version;
    }

    /**
     * Getter for <code>spam_word.text</code>.
     */
    public String getText() {
        return this.text;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final SpamWord other = (SpamWord) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.version == null) {
            if (other.version != null)
                return false;
        }
        else if (!this.version.equals(other.version))
            return false;
        if (this.text == null) {
            if (other.text != null)
                return false;
        }
        else if (!this.text.equals(other.text))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.version == null) ? 0 : this.version.hashCode());
        result = prime * result + ((this.text == null) ? 0 : this.text.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("SpamWord (");

        sb.append(id);
        sb.append(", ").append(version);
        sb.append(", ").append(text);

        sb.append(")");
        return sb.toString();
    }
}
