/*
 * This file is generated by jOOQ.
 */
package com.chatcode.jooq.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TempArticle implements Serializable {

    private static final long serialVersionUID = 1L;

    private final Long id;
    private final Long avatarId;
    private final String title;
    private final String content;
    private final LocalDateTime dateLastSaved;
    private final Integer status;

    public TempArticle(TempArticle value) {
        this.id = value.id;
        this.avatarId = value.avatarId;
        this.title = value.title;
        this.content = value.content;
        this.dateLastSaved = value.dateLastSaved;
        this.status = value.status;
    }

    public TempArticle(
        Long id,
        Long avatarId,
        String title,
        String content,
        LocalDateTime dateLastSaved,
        Integer status
    ) {
        this.id = id;
        this.avatarId = avatarId;
        this.title = title;
        this.content = content;
        this.dateLastSaved = dateLastSaved;
        this.status = status;
    }

    /**
     * Getter for <code>temp_article.id</code>.
     */
    public Long getId() {
        return this.id;
    }

    /**
     * Getter for <code>temp_article.avatar_id</code>.
     */
    public Long getAvatarId() {
        return this.avatarId;
    }

    /**
     * Getter for <code>temp_article.title</code>.
     */
    public String getTitle() {
        return this.title;
    }

    /**
     * Getter for <code>temp_article.content</code>.
     */
    public String getContent() {
        return this.content;
    }

    /**
     * Getter for <code>temp_article.date_last_saved</code>.
     */
    public LocalDateTime getDateLastSaved() {
        return this.dateLastSaved;
    }

    /**
     * Getter for <code>temp_article.status</code>.
     */
    public Integer getStatus() {
        return this.status;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final TempArticle other = (TempArticle) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.avatarId == null) {
            if (other.avatarId != null)
                return false;
        }
        else if (!this.avatarId.equals(other.avatarId))
            return false;
        if (this.title == null) {
            if (other.title != null)
                return false;
        }
        else if (!this.title.equals(other.title))
            return false;
        if (this.content == null) {
            if (other.content != null)
                return false;
        }
        else if (!this.content.equals(other.content))
            return false;
        if (this.dateLastSaved == null) {
            if (other.dateLastSaved != null)
                return false;
        }
        else if (!this.dateLastSaved.equals(other.dateLastSaved))
            return false;
        if (this.status == null) {
            if (other.status != null)
                return false;
        }
        else if (!this.status.equals(other.status))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.avatarId == null) ? 0 : this.avatarId.hashCode());
        result = prime * result + ((this.title == null) ? 0 : this.title.hashCode());
        result = prime * result + ((this.content == null) ? 0 : this.content.hashCode());
        result = prime * result + ((this.dateLastSaved == null) ? 0 : this.dateLastSaved.hashCode());
        result = prime * result + ((this.status == null) ? 0 : this.status.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("TempArticle (");

        sb.append(id);
        sb.append(", ").append(avatarId);
        sb.append(", ").append(title);
        sb.append(", ").append(content);
        sb.append(", ").append(dateLastSaved);
        sb.append(", ").append(status);

        sb.append(")");
        return sb.toString();
    }
}
