/*
 * This file is generated by jOOQ.
 */
package com.chatcode.jooq.tables.records;


import com.chatcode.jooq.tables.AreaCityCode;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AreaCityCodeRecord extends UpdatableRecordImpl<AreaCityCodeRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>area_city_code.id</code>.
     */
    public AreaCityCodeRecord setId(String value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>area_city_code.id</code>.
     */
    public String getId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>area_city_code.version</code>.
     */
    public AreaCityCodeRecord setVersion(Long value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>area_city_code.version</code>.
     */
    public Long getVersion() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>area_city_code.name</code>.
     */
    public AreaCityCodeRecord setName(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>area_city_code.name</code>.
     */
    public String getName() {
        return (String) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached AreaCityCodeRecord
     */
    public AreaCityCodeRecord() {
        super(AreaCityCode.AREA_CITY_CODE);
    }

    /**
     * Create a detached, initialised AreaCityCodeRecord
     */
    public AreaCityCodeRecord(String id, Long version, String name) {
        super(AreaCityCode.AREA_CITY_CODE);

        setId(id);
        setVersion(version);
        setName(name);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised AreaCityCodeRecord
     */
    public AreaCityCodeRecord(com.chatcode.jooq.tables.pojos.AreaCityCode value) {
        super(AreaCityCode.AREA_CITY_CODE);

        if (value != null) {
            setId(value.getId());
            setVersion(value.getVersion());
            setName(value.getName());
            resetChangedOnNotNull();
        }
    }
}
