/*
 * This file is generated by jOOQ.
 */
package com.chatcode.jooq.tables.records;


import com.chatcode.jooq.tables.AvatarInterestTag;

import org.jooq.Record2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AvatarInterestTagRecord extends UpdatableRecordImpl<AvatarInterestTagRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>avatar_interest_tag.avatar_id</code>.
     */
    public AvatarInterestTagRecord setAvatarId(Long value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>avatar_interest_tag.avatar_id</code>.
     */
    public Long getAvatarId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>avatar_interest_tag.interest_tag_id</code>.
     */
    public AvatarInterestTagRecord setInterestTagId(Long value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>avatar_interest_tag.interest_tag_id</code>.
     */
    public Long getInterestTagId() {
        return (Long) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record2<Long, Long> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached AvatarInterestTagRecord
     */
    public AvatarInterestTagRecord() {
        super(AvatarInterestTag.AVATAR_INTEREST_TAG);
    }

    /**
     * Create a detached, initialised AvatarInterestTagRecord
     */
    public AvatarInterestTagRecord(Long avatarId, Long interestTagId) {
        super(AvatarInterestTag.AVATAR_INTEREST_TAG);

        setAvatarId(avatarId);
        setInterestTagId(interestTagId);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised AvatarInterestTagRecord
     */
    public AvatarInterestTagRecord(com.chatcode.jooq.tables.pojos.AvatarInterestTag value) {
        super(AvatarInterestTag.AVATAR_INTEREST_TAG);

        if (value != null) {
            setAvatarId(value.getAvatarId());
            setInterestTagId(value.getInterestTagId());
            resetChangedOnNotNull();
        }
    }
}
