/*
 * This file is generated by jOOQ.
 */
package com.chatcode.jooq.tables.records;


import com.chatcode.jooq.tables.Avatar;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AvatarRecord extends UpdatableRecordImpl<AvatarRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>avatar.id</code>.
     */
    public AvatarRecord setId(Long value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>avatar.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>avatar.version</code>.
     */
    public AvatarRecord setVersion(Long value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>avatar.version</code>.
     */
    public Long getVersion() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>avatar.activity_point</code>.
     */
    public AvatarRecord setActivityPoint(Integer value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>avatar.activity_point</code>.
     */
    public Integer getActivityPoint() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>avatar.nickname</code>.
     */
    public AvatarRecord setNickname(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>avatar.nickname</code>.
     */
    public String getNickname() {
        return (String) get(3);
    }

    /**
     * Setter for <code>avatar.picture</code>.
     */
    public AvatarRecord setPicture(String value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>avatar.picture</code>.
     */
    public String getPicture() {
        return (String) get(4);
    }

    /**
     * Setter for <code>avatar.content</code>.
     */
    public AvatarRecord setContent(String value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>avatar.content</code>.
     */
    public String getContent() {
        return (String) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached AvatarRecord
     */
    public AvatarRecord() {
        super(Avatar.AVATAR);
    }

    /**
     * Create a detached, initialised AvatarRecord
     */
    public AvatarRecord(Long id, Long version, Integer activityPoint, String nickname, String picture, String content) {
        super(Avatar.AVATAR);

        setId(id);
        setVersion(version);
        setActivityPoint(activityPoint);
        setNickname(nickname);
        setPicture(picture);
        setContent(content);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised AvatarRecord
     */
    public AvatarRecord(com.chatcode.jooq.tables.pojos.Avatar value) {
        super(Avatar.AVATAR);

        if (value != null) {
            setId(value.getId());
            setVersion(value.getVersion());
            setActivityPoint(value.getActivityPoint());
            setNickname(value.getNickname());
            setPicture(value.getPicture());
            setContent(value.getContent());
            resetChangedOnNotNull();
        }
    }
}
