/*
 * This file is generated by jOOQ.
 */
package com.chatcode.jooq.tables.records;


import com.chatcode.jooq.tables.Banner;

import java.time.LocalDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class BannerRecord extends UpdatableRecordImpl<BannerRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>banner.id</code>.
     */
    public BannerRecord setId(Long value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>banner.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>banner.version</code>.
     */
    public BannerRecord setVersion(Long value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>banner.version</code>.
     */
    public Long getVersion() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>banner.date_created</code>.
     */
    public BannerRecord setDateCreated(LocalDateTime value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>banner.date_created</code>.
     */
    public LocalDateTime getDateCreated() {
        return (LocalDateTime) get(2);
    }

    /**
     * Setter for <code>banner.image</code>.
     */
    public BannerRecord setImage(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>banner.image</code>.
     */
    public String getImage() {
        return (String) get(3);
    }

    /**
     * Setter for <code>banner.last_updated</code>.
     */
    public BannerRecord setLastUpdated(LocalDateTime value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>banner.last_updated</code>.
     */
    public LocalDateTime getLastUpdated() {
        return (LocalDateTime) get(4);
    }

    /**
     * Setter for <code>banner.name</code>.
     */
    public BannerRecord setName(String value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>banner.name</code>.
     */
    public String getName() {
        return (String) get(5);
    }

    /**
     * Setter for <code>banner.target</code>.
     */
    public BannerRecord setTarget(String value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>banner.target</code>.
     */
    public String getTarget() {
        return (String) get(6);
    }

    /**
     * Setter for <code>banner.type</code>.
     */
    public BannerRecord setType(String value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for <code>banner.type</code>.
     */
    public String getType() {
        return (String) get(7);
    }

    /**
     * Setter for <code>banner.url</code>.
     */
    public BannerRecord setUrl(String value) {
        set(8, value);
        return this;
    }

    /**
     * Getter for <code>banner.url</code>.
     */
    public String getUrl() {
        return (String) get(8);
    }

    /**
     * Setter for <code>banner.visible</code>.
     */
    public BannerRecord setVisible(Boolean value) {
        set(9, value);
        return this;
    }

    /**
     * Getter for <code>banner.visible</code>.
     */
    public Boolean getVisible() {
        return (Boolean) get(9);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached BannerRecord
     */
    public BannerRecord() {
        super(Banner.BANNER);
    }

    /**
     * Create a detached, initialised BannerRecord
     */
    public BannerRecord(Long id, Long version, LocalDateTime dateCreated, String image, LocalDateTime lastUpdated, String name, String target, String type, String url, Boolean visible) {
        super(Banner.BANNER);

        setId(id);
        setVersion(version);
        setDateCreated(dateCreated);
        setImage(image);
        setLastUpdated(lastUpdated);
        setName(name);
        setTarget(target);
        setType(type);
        setUrl(url);
        setVisible(visible);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised BannerRecord
     */
    public BannerRecord(com.chatcode.jooq.tables.pojos.Banner value) {
        super(Banner.BANNER);

        if (value != null) {
            setId(value.getId());
            setVersion(value.getVersion());
            setDateCreated(value.getDateCreated());
            setImage(value.getImage());
            setLastUpdated(value.getLastUpdated());
            setName(value.getName());
            setTarget(value.getTarget());
            setType(value.getType());
            setUrl(value.getUrl());
            setVisible(value.getVisible());
            resetChangedOnNotNull();
        }
    }
}
