/*
 * This file is generated by jOOQ.
 */
package com.chatcode.jooq.tables.records;


import com.chatcode.jooq.tables.BannerClick;

import java.time.LocalDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class BannerClickRecord extends UpdatableRecordImpl<BannerClickRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>banner_click.id</code>.
     */
    public BannerClickRecord setId(Long value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>banner_click.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>banner_click.version</code>.
     */
    public BannerClickRecord setVersion(Long value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>banner_click.version</code>.
     */
    public Long getVersion() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>banner_click.banner_id</code>.
     */
    public BannerClickRecord setBannerId(Long value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>banner_click.banner_id</code>.
     */
    public Long getBannerId() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>banner_click.click_count</code>.
     */
    public BannerClickRecord setClickCount(Integer value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>banner_click.click_count</code>.
     */
    public Integer getClickCount() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>banner_click.date_created</code>.
     */
    public BannerClickRecord setDateCreated(LocalDateTime value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>banner_click.date_created</code>.
     */
    public LocalDateTime getDateCreated() {
        return (LocalDateTime) get(4);
    }

    /**
     * Setter for <code>banner_click.ip</code>.
     */
    public BannerClickRecord setIp(String value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>banner_click.ip</code>.
     */
    public String getIp() {
        return (String) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached BannerClickRecord
     */
    public BannerClickRecord() {
        super(BannerClick.BANNER_CLICK);
    }

    /**
     * Create a detached, initialised BannerClickRecord
     */
    public BannerClickRecord(Long id, Long version, Long bannerId, Integer clickCount, LocalDateTime dateCreated, String ip) {
        super(BannerClick.BANNER_CLICK);

        setId(id);
        setVersion(version);
        setBannerId(bannerId);
        setClickCount(clickCount);
        setDateCreated(dateCreated);
        setIp(ip);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised BannerClickRecord
     */
    public BannerClickRecord(com.chatcode.jooq.tables.pojos.BannerClick value) {
        super(BannerClick.BANNER_CLICK);

        if (value != null) {
            setId(value.getId());
            setVersion(value.getVersion());
            setBannerId(value.getBannerId());
            setClickCount(value.getClickCount());
            setDateCreated(value.getDateCreated());
            setIp(value.getIp());
            resetChangedOnNotNull();
        }
    }
}
