/*
 * This file is generated by jOOQ.
 */
package com.chatcode.jooq.tables.records;


import com.chatcode.jooq.tables.Category;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CategoryRecord extends UpdatableRecordImpl<CategoryRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>category.code</code>.
     */
    public CategoryRecord setCode(String value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>category.code</code>.
     */
    public String getCode() {
        return (String) get(0);
    }

    /**
     * Setter for <code>category.name</code>.
     */
    public CategoryRecord setName(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>category.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>category.sort_order</code>.
     */
    public CategoryRecord setSortOrder(Integer value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>category.sort_order</code>.
     */
    public Integer getSortOrder() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>category.type</code>.
     */
    public CategoryRecord setType(Integer value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>category.type</code>.
     */
    public Integer getType() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>category.parent_id</code>.
     */
    public CategoryRecord setParentId(Integer value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>category.parent_id</code>.
     */
    public Integer getParentId() {
        return (Integer) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached CategoryRecord
     */
    public CategoryRecord() {
        super(Category.CATEGORY);
    }

    /**
     * Create a detached, initialised CategoryRecord
     */
    public CategoryRecord(String code, String name, Integer sortOrder, Integer type, Integer parentId) {
        super(Category.CATEGORY);

        setCode(code);
        setName(name);
        setSortOrder(sortOrder);
        setType(type);
        setParentId(parentId);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised CategoryRecord
     */
    public CategoryRecord(com.chatcode.jooq.tables.pojos.Category value) {
        super(Category.CATEGORY);

        if (value != null) {
            setCode(value.getCode());
            setName(value.getName());
            setSortOrder(value.getSortOrder());
            setType(value.getType());
            setParentId(value.getParentId());
            resetChangedOnNotNull();
        }
    }
}
