/*
 * This file is generated by jOOQ.
 */
package com.chatcode.jooq.tables.records;


import com.chatcode.jooq.tables.ContentFile;

import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ContentFileRecord extends TableRecordImpl<ContentFileRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>content_file.content_files_id</code>.
     */
    public ContentFileRecord setContentFilesId(Long value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>content_file.content_files_id</code>.
     */
    public Long getContentFilesId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>content_file.file_id</code>.
     */
    public ContentFileRecord setFileId(Long value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>content_file.file_id</code>.
     */
    public Long getFileId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>content_file.Key</code>.
     */
    public ContentFileRecord setKey(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>content_file.Key</code>.
     */
    public String getKey() {
        return (String) get(2);
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ContentFileRecord
     */
    public ContentFileRecord() {
        super(ContentFile.CONTENT_FILE);
    }

    /**
     * Create a detached, initialised ContentFileRecord
     */
    public ContentFileRecord(Long contentFilesId, Long fileId, String key) {
        super(ContentFile.CONTENT_FILE);

        setContentFilesId(contentFilesId);
        setFileId(fileId);
        setKey(key);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised ContentFileRecord
     */
    public ContentFileRecord(com.chatcode.jooq.tables.pojos.ContentFile value) {
        super(ContentFile.CONTENT_FILE);

        if (value != null) {
            setContentFilesId(value.getContentFilesId());
            setFileId(value.getFileId());
            setKey(value.getKey());
            resetChangedOnNotNull();
        }
    }
}
