/*
 * This file is generated by jOOQ.
 */
package com.chatcode.jooq.tables.records;


import com.chatcode.jooq.tables.File;

import java.time.LocalDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class FileRecord extends UpdatableRecordImpl<FileRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>file.id</code>.
     */
    public FileRecord setId(Long value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>file.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>file.url</code>.
     */
    public FileRecord setUrl(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>file.url</code>.
     */
    public String getUrl() {
        return (String) get(1);
    }

    /**
     * Setter for <code>file.target_id</code>.
     */
    public FileRecord setTargetId(Long value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>file.target_id</code>.
     */
    public Long getTargetId() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>file.date_created</code>.
     */
    public FileRecord setDateCreated(LocalDateTime value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>file.date_created</code>.
     */
    public LocalDateTime getDateCreated() {
        return (LocalDateTime) get(3);
    }

    /**
     * Setter for <code>file.last_updated</code>.
     */
    public FileRecord setLastUpdated(LocalDateTime value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>file.last_updated</code>.
     */
    public LocalDateTime getLastUpdated() {
        return (LocalDateTime) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached FileRecord
     */
    public FileRecord() {
        super(File.FILE);
    }

    /**
     * Create a detached, initialised FileRecord
     */
    public FileRecord(Long id, String url, Long targetId, LocalDateTime dateCreated, LocalDateTime lastUpdated) {
        super(File.FILE);

        setId(id);
        setUrl(url);
        setTargetId(targetId);
        setDateCreated(dateCreated);
        setLastUpdated(lastUpdated);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised FileRecord
     */
    public FileRecord(com.chatcode.jooq.tables.pojos.File value) {
        super(File.FILE);

        if (value != null) {
            setId(value.getId());
            setUrl(value.getUrl());
            setTargetId(value.getTargetId());
            setDateCreated(value.getDateCreated());
            setLastUpdated(value.getLastUpdated());
            resetChangedOnNotNull();
        }
    }
}
