/*
 * This file is generated by jOOQ.
 */
package com.chatcode.jooq.tables.records;


import com.chatcode.jooq.tables.Oauthid;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class OauthidRecord extends UpdatableRecordImpl<OauthidRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>oauthid.id</code>.
     */
    public OauthidRecord setId(Long value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>oauthid.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>oauthid.user_id</code>.
     */
    public OauthidRecord setUserId(Long value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>oauthid.user_id</code>.
     */
    public Long getUserId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>oauthid.version</code>.
     */
    public OauthidRecord setVersion(Long value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>oauthid.version</code>.
     */
    public Long getVersion() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>oauthid.access_token</code>.
     */
    public OauthidRecord setAccessToken(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>oauthid.access_token</code>.
     */
    public String getAccessToken() {
        return (String) get(3);
    }

    /**
     * Setter for <code>oauthid.provider</code>.
     */
    public OauthidRecord setProvider(String value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>oauthid.provider</code>.
     */
    public String getProvider() {
        return (String) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached OauthidRecord
     */
    public OauthidRecord() {
        super(Oauthid.OAUTHID);
    }

    /**
     * Create a detached, initialised OauthidRecord
     */
    public OauthidRecord(Long id, Long userId, Long version, String accessToken, String provider) {
        super(Oauthid.OAUTHID);

        setId(id);
        setUserId(userId);
        setVersion(version);
        setAccessToken(accessToken);
        setProvider(provider);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised OauthidRecord
     */
    public OauthidRecord(com.chatcode.jooq.tables.pojos.Oauthid value) {
        super(Oauthid.OAUTHID);

        if (value != null) {
            setId(value.getId());
            setUserId(value.getUserId());
            setVersion(value.getVersion());
            setAccessToken(value.getAccessToken());
            setProvider(value.getProvider());
            resetChangedOnNotNull();
        }
    }
}
