/*
 * This file is generated by jOOQ.
 */
package com.chatcode.jooq.tables.records;


import com.chatcode.jooq.tables.Tag;

import java.time.LocalDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TagRecord extends UpdatableRecordImpl<TagRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>tag.id</code>.
     */
    public TagRecord setId(Long value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>tag.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>tag.date_created</code>.
     */
    public TagRecord setDateCreated(LocalDateTime value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>tag.date_created</code>.
     */
    public LocalDateTime getDateCreated() {
        return (LocalDateTime) get(1);
    }

    /**
     * Setter for <code>tag.description</code>.
     */
    public TagRecord setDescription(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>tag.description</code>.
     */
    public String getDescription() {
        return (String) get(2);
    }

    /**
     * Setter for <code>tag.name</code>.
     */
    public TagRecord setName(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>tag.name</code>.
     */
    public String getName() {
        return (String) get(3);
    }

    /**
     * Setter for <code>tag.tagged_count</code>.
     */
    public TagRecord setTaggedCount(Integer value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>tag.tagged_count</code>.
     */
    public Integer getTaggedCount() {
        return (Integer) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TagRecord
     */
    public TagRecord() {
        super(Tag.TAG);
    }

    /**
     * Create a detached, initialised TagRecord
     */
    public TagRecord(Long id, LocalDateTime dateCreated, String description, String name, Integer taggedCount) {
        super(Tag.TAG);

        setId(id);
        setDateCreated(dateCreated);
        setDescription(description);
        setName(name);
        setTaggedCount(taggedCount);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised TagRecord
     */
    public TagRecord(com.chatcode.jooq.tables.pojos.Tag value) {
        super(Tag.TAG);

        if (value != null) {
            setId(value.getId());
            setDateCreated(value.getDateCreated());
            setDescription(value.getDescription());
            setName(value.getName());
            setTaggedCount(value.getTaggedCount());
            resetChangedOnNotNull();
        }
    }
}
