/*
 * This file is generated by jOOQ.
 */
package com.chatcode.jooq.tables.records;


import com.chatcode.jooq.tables.UserRole;

import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserRoleRecord extends TableRecordImpl<UserRoleRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>CHATCODE.user_role.user_id</code>.
     */
    public UserRoleRecord setUserId(Long value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>CHATCODE.user_role.user_id</code>.
     */
    public Long getUserId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>CHATCODE.user_role.role_id</code>.
     */
    public UserRoleRecord setRoleId(Long value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>CHATCODE.user_role.role_id</code>.
     */
    public Long getRoleId() {
        return (Long) get(1);
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached UserRoleRecord
     */
    public UserRoleRecord() {
        super(UserRole.USER_ROLE);
    }

    /**
     * Create a detached, initialised UserRoleRecord
     */
    public UserRoleRecord(Long userId, Long roleId) {
        super(UserRole.USER_ROLE);

        setUserId(userId);
        setRoleId(roleId);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised UserRoleRecord
     */
    public UserRoleRecord(com.chatcode.jooq.tables.pojos.UserRole value) {
        super(UserRole.USER_ROLE);

        if (value != null) {
            setUserId(value.getUserId());
            setRoleId(value.getRoleId());
            resetChangedOnNotNull();
        }
    }
}
